### ISSUE TITLE
peas_shell logging errors

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#267]
After updating POCS on PAN006 to include the piaa imaging fix, peas_shell is still spewing logging related errors.

```python
panoptes@Panmass:/var/panoptes/POCS$ bin/peas_shell 
Welcome to PEAS Shell! Type ? for help
PEAS > load_environment
Loading sensors
PEAS > load_weather
Loading AAG Cloud Sensor on /dev/ttyUSB1
--- Logging error ---
Traceback (most recent call last):
  File "/home/panoptes/anaconda3/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/home/panoptes/anaconda3/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/home/panoptes/anaconda3/lib/python3.6/logging/__init__.py", line 578, in format
    s = self.formatMessage(record)
  File "/home/panoptes/anaconda3/lib/python3.6/logging/__init__.py", line 547, in formatMessage
    return self._style.format(record)
  File "/home/panoptes/anaconda3/lib/python3.6/logging/__init__.py", line 399, in format
    return self._fmt.format(**record.__dict__)
KeyError: 'fileline'
Call stack:
  File "bin/peas_shell", line 296, in <module>
    PanSensorShell().cmdloop()
  File "/home/panoptes/anaconda3/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/home/panoptes/anaconda3/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "bin/peas_shell", line 148, in do_load_weather
    self.weather = AAGCloudSensor(serial_address=port, use_mongo=True)
  File "/var/panoptes/POCS/peas/weather.py", line 127, in __init__
    self.logger.info('Connecting to AAG Cloud Sensor')
Message: 'Connecting to AAG Cloud Sensor'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/home/panoptes/anaconda3/lib/python3.6/logging/__init__.py", line 992, in emit
    msg = self.format(record)
  File "/home/panoptes/anaconda3/lib/python3.6/logging/__init__.py", line 838, in format
    return fmt.format(record)
  File "/home/panoptes/anaconda3/lib/python3.6/logging/__init__.py", line 578, in format
    s = self.formatMessage(record)
  File "/home/panoptes/anaconda3/lib/python3.6/logging/__init__.py", line 547, in formatMessage
    return self._style.format(record)
  File "/home/panoptes/anaconda3/lib/python3.6/logging/__init__.py", line 399, in format
    return self._fmt.format(**record.__dict__)
KeyError: 'fileline'
Call stack:
  File "bin/peas_shell", line 296, in <module>
    PanSensorShell().cmdloop()
  File "/home/panoptes/anaconda3/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/home/panoptes/anaconda3/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "bin/peas_shell", line 148, in do_load_weather
    self.weather = AAGCloudSensor(serial_address=port, use_mongo=True)
  File "/var/panoptes/POCS/peas/weather.py", line 130, in __init__
    self.logger.info("  Connected to Cloud Sensor on {}".format(serial_address))
Message: '  Connected to Cloud Sensor on /dev/ttyUSB1'
Arguments: ()
```

**Comment by jamessynge** [comment]
Fixed by #269
