### ISSUE TITLE
pocs_shell exit hanging

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#508]
The log file showed no activity after I entered exit, but pocs_shell did not stop. It looks like it might have been waiting 30 minutes for the sky to be clear... in part because it hadn't detected that I'd changed pocs_local.yaml to point to a new targets file.

This is the output in the terminal:

```
POCS > run_pocs                                                                                                     
Starting POCS - Press Ctrl-c to interrupt
^CPOCS interrupted, skipping states and parking
POCS stopped.
POCS > exit
Shutting down POCS instance, please wait
^CTraceback (most recent call last):
  File "bin/pocs_shell", line 899, in <module>
    PocsShell().cmdloop()
  File "/home/panoptes/anaconda3/envs/panoptes-env/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/home/panoptes/anaconda3/envs/panoptes-env/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "bin/pocs_shell", line 256, in do_exit
    self.do_power_down()
  File "bin/pocs_shell", line 332, in do_power_down
    self.pocs.power_down()
  File "/var/panoptes/POCS/pocs/core.py", line 243, in power_down
    self.set_park()
  File "/home/panoptes/anaconda3/envs/panoptes-env/lib/python3.6/site-packages/transitions/core.py", line 382, in trigger
    return self.machine._process(func)
  File "/home/panoptes/anaconda3/envs/panoptes-env/lib/python3.6/site-packages/transitions/core.py", line 1007, in _process
    return trigger()
  File "/home/panoptes/anaconda3/envs/panoptes-env/lib/python3.6/site-packages/transitions/core.py", line 398, in _trigger
    return self._process(event_data)
  File "/home/panoptes/anaconda3/envs/panoptes-env/lib/python3.6/site-packages/transitions/core.py", line 408, in _process
    if trans.execute(event_data):
  File "/home/panoptes/anaconda3/envs/panoptes-env/lib/python3.6/site-packages/transitions/core.py", line 262, in execute
    self._change_state(event_data)
  File "/home/panoptes/anaconda3/envs/panoptes-env/lib/python3.6/site-packages/transitions/core.py", line 273, in _change_state
    event_data.machine.get_state(self.dest).enter(event_data)
  File "/home/panoptes/anaconda3/envs/panoptes-env/lib/python3.6/site-packages/transitions/core.py", line 119, in enter
    event_data.machine.callback(handle, event_data)
  File "/home/panoptes/anaconda3/envs/panoptes-env/lib/python3.6/site-packages/transitions/core.py", line 988, in callback
    func(event_data)
  File "/var/panoptes/POCS/pocs/state/states/default/parked.py", line 28, in on_enter
    pocs.sleep(delay=1800)  # 30 minutes = 1800 seconds
  File "/var/panoptes/POCS/pocs/core.py", line 430, in sleep
    time.sleep(10.0)
KeyboardInterrupt
--- Logging error ---
Traceback (most recent call last):
  File "/home/panoptes/anaconda3/envs/panoptes-env/lib/python3.6/logging/handlers.py", line 73, in emit
    logging.FileHandler.emit(self, record)
  File "/home/panoptes/anaconda3/envs/panoptes-env/lib/python3.6/logging/__init__.py", line 1069, in emit
    self.stream = self._open()
  File "/home/panoptes/anaconda3/envs/panoptes-env/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
NameError: name 'open' is not defined
Call stack:
  File "/var/panoptes/POCS/pocs/dome/abstract_serial_dome.py", line 42, in __del__
    self.serial.disconnect()
  File "/var/panoptes/POCS/pocs/utils/rs232.py", line 156, in disconnect
    self.logger.debug('SerialData.disconnect called for {}', self.name)
Message: 'SerialData.disconnect called for {}'
Arguments: ('/dev/ttyUSB2',)
(panoptes-env) panoptes@Panmass:/var/panoptes/POCS ((30a2828...))$ 
```

And this is the end of the log file:

```
E0326 23:54:37.009 error.py:18          NoObservation: No valid observations found
I0326 23:54:37.011 messaging.py:134     PANCHAT No valid observations found. Can't schedule. Going to park.
D0326 23:54:37.012 machine.py:267       After calling schedule. Now in scheduling state
D0326 23:54:37.014 machine.py:309       Source: scheduling	 Dest: parking
D0326 23:54:37.014 machine.py:171       Transition method: park
D0326 23:54:37.014 machine.py:209       Checking safety for park
D0326 23:54:37.014 machine.py:214       Always safe to move to park
D0326 23:54:37.014 machine.py:253       Before calling park from scheduling state
I0326 23:54:42.170 scheduler.py:116     Setting new observation to None
I0326 23:54:42.170 messaging.py:134     PANCHAT Closing dome
D0326 23:54:42.171 abstract_serial_dome.py:70 Already connected to dome
I0326 23:54:42.520 observatory.py:536   Closed dome
D0326 23:54:49.592 astrohaven.py:183    Got target_feedback, feedback_countdown=1
D0326 23:54:50.001 astrohaven.py:183    Got target_feedback, feedback_countdown=0
D0326 23:54:57.281 astrohaven.py:183    Got target_feedback, feedback_countdown=1
D0326 23:54:57.691 astrohaven.py:183    Got target_feedback, feedback_countdown=0
I0326 23:55:00.591 messaging.py:134     PANCHAT I'm takin' it on home and then parking.
D0326 23:55:08.114 mount.py:356         Slewing to home, sleeping for 5 seconds
D0326 23:55:15.132 mount.py:356         Slewing to home, sleeping for 5 seconds
D0326 23:55:22.155 mount.py:356         Slewing to home, sleeping for 5 seconds
I0326 23:55:24.170 ioptron.py:141       Initializing pocs.mount.ioptron mount
I0326 23:55:25.172 ioptron.py:244       Setting up mount for location
D0326 23:55:28.184 serial.py:88         Setting tracking rate to sidereal +00.0000
D0326 23:55:28.686 serial.py:90         Custom tracking rate set
D0326 23:55:29.187 serial.py:94         Tracking response: 1
D0326 23:55:29.188 serial.py:98         Custom tracking rate sent
D0326 23:55:29.188 ioptron.py:212       Setting manual moving rate to max
D0326 23:55:30.190 ioptron.py:214       Mount guide rate: 5050
D0326 23:55:31.192 ioptron.py:220       Mount guide rate: 0.5 0.5
I0326 23:55:31.193 ioptron.py:167       Mount initialized: True
D0326 23:55:31.193 mount.py:228         Setting park position
D0326 23:55:31.204 mount.py:234         LST: 7.471357350520564 hourangle
D0326 23:55:31.204 mount.py:235         HA: -170.0 deg
D0326 23:55:31.205 mount.py:238         RA: 18.8046906838539 hourangle
D0326 23:55:31.205 mount.py:239         Dec: -10.0 deg
D0326 23:55:31.210 mount.py:243         Park Coordinates RA-Dec: <SkyCoord (ICRS): (ra, dec) in deg
    ( 282.07036026, -10.)>
D0326 23:55:31.210 mount.py:266         Setting target coordinates: <SkyCoord (ICRS): (ra, dec) in deg
    ( 282.07036026, -10.)>
D0326 23:55:31.211 ioptron.py:322       RA (ms): 67696886.46187404 ms
D0326 23:55:31.212 ioptron.py:325       Dec (centiarcsec): -3600000.0 carcsec
D0326 23:55:32.714 ioptron.py:187       Slewing to park
D0326 23:55:53.303 mount.py:460         Mount unparked
D0326 23:55:53.804 mount.py:474         Move command: move_south
D0326 23:55:53.805 mount.py:478         Moving south for 11.0 seconds. 
D0326 23:56:07.316 mount.py:483         13.509153999996926 seconds passed before stop
D0326 23:56:07.818 mount.py:485         14.0126439999964 seconds passed total
D0326 23:56:07.818 mount.py:493         Stopping movement
D0326 23:56:10.328 mount.py:368         Mount parked
D0326 23:56:10.329 machine.py:267       After calling park. Now in parking state
D0326 23:56:10.333 machine.py:309       Source: parking	 Dest: parked
D0326 23:56:10.333 machine.py:171       Transition method: set_park
D0326 23:56:10.334 machine.py:209       Checking safety for set_park
D0326 23:56:10.334 machine.py:214       Always safe to move to set_park
D0326 23:56:10.334 machine.py:253       Before calling set_park from parking state
I0326 23:56:15.277 messaging.py:134     PANCHAT I'm parked now. Phew.
I0326 23:56:15.278 messaging.py:134     PANCHAT No observations found.
I0326 23:56:15.279 messaging.py:134     PANCHAT Going to stay parked for half an hour then will try again.
D0327 00:26:21.884 core.py:336          Dark Check: True
D0327 00:26:21.884 core.py:351          Checking weather safety
D0327 00:26:21.886 core.py:371          Weather Safety: True [31 sec old - 2018-03-27 00:25:51.207000]
D0327 00:26:21.887 core.py:267          Resetting observing run attempts
D0327 00:26:21.887 machine.py:267       After calling set_park. Now in parked state
D0327 00:26:21.890 machine.py:309       Source: parked	 Dest: ready
D0327 00:26:21.891 machine.py:171       Transition method: get_ready
D0327 00:26:21.891 machine.py:209       Checking safety for get_ready
D0327 00:26:21.891 machine.py:214       Always safe to move to get_ready
D0327 00:26:21.891 machine.py:253       Before calling get_ready from parked state
I0327 00:26:26.288 messaging.py:134     PANCHAT Ok, I'm all set up and ready to go!
D0327 00:26:26.289 abstract_serial_dome.py:70 Already connected to dome
I0327 00:26:26.620 observatory.py:522   Opening dome
D0327 00:26:33.922 astrohaven.py:183    Got target_feedback, feedback_countdown=1
D0327 00:26:34.331 astrohaven.py:183    Got target_feedback, feedback_countdown=0
D0327 00:26:41.430 astrohaven.py:183    Got target_feedback, feedback_countdown=1
D0327 00:26:41.840 astrohaven.py:183    Got target_feedback, feedback_countdown=0
D0327 00:26:45.242 mount.py:460         Mount unparked
D0327 00:26:45.242 machine.py:267       After calling get_ready. Now in ready state
D0327 00:26:45.244 machine.py:309       Source: ready	 Dest: scheduling
D0327 00:26:45.244 machine.py:171       Transition method: schedule
D0327 00:26:45.244 machine.py:209       Checking safety for schedule
D0327 00:26:45.355 core.py:336          Dark Check: True
D0327 00:26:45.355 core.py:351          Checking weather safety
D0327 00:26:45.356 core.py:371          Weather Safety: True [54 sec old - 2018-03-27 00:25:51.207000]
D0327 00:26:45.356 machine.py:253       Before calling schedule from ready state
I0327 00:26:50.802 messaging.py:134     PANCHAT Ok, I'm finding something good to look at...
D0327 00:26:50.802 observatory.py:186   Getting observation for observatory
D0327 00:26:50.803 scheduler.py:255     Reading fields from file: /var/panoptes/POCS/resources/targets/2018-03-11.yaml
D0327 00:26:50.805 scheduler.py:227     Adding Tres 3 to scheduler
D0327 00:26:50.868 observation.py:76    Observation created: Tres 3: 120.0 s exposures in blocks of 10, minimum 60, priority 300
I0327 00:26:51.646 dispatch.py:54       Checking Constraint: Altitude
D0327 00:26:51.646 dispatch.py:57       	Observation: Tres 3
D0327 00:26:51.712 constraint.py:61     		Below minimum altitude: -5.39 < 20.00
D0327 00:26:51.713 dispatch.py:62       		Score: 0.00000	Veto: True
D0327 00:26:51.713 dispatch.py:65       		Tres 3 vetoed by Altitude
I0327 00:26:51.713 dispatch.py:54       Checking Constraint: Moon Avoidance
I0327 00:26:51.713 dispatch.py:54       Checking Constraint: Duration above 20.0 deg
I0327 00:26:51.713 scheduler.py:116     Setting new observation to None
E0327 00:26:51.724 error.py:18          NoObservation: No valid observations found
I0327 00:26:51.724 messaging.py:134     PANCHAT No valid observations found. Can't schedule. Going to park.
D0327 00:26:51.724 machine.py:267       After calling schedule. Now in scheduling state
D0327 00:26:51.727 machine.py:309       Source: scheduling	 Dest: parking
D0327 00:26:51.727 machine.py:171       Transition method: park
D0327 00:26:51.727 machine.py:209       Checking safety for park
D0327 00:26:51.727 machine.py:214       Always safe to move to park
D0327 00:26:51.727 machine.py:253       Before calling park from scheduling state
I0327 00:26:56.436 scheduler.py:116     Setting new observation to None
I0327 00:26:56.437 messaging.py:134     PANCHAT Closing dome
D0327 00:26:56.437 abstract_serial_dome.py:70 Already connected to dome
I0327 00:26:56.741 observatory.py:536   Closed dome
D0327 00:27:04.414 astrohaven.py:183    Got target_feedback, feedback_countdown=1
D0327 00:27:04.824 astrohaven.py:183    Got target_feedback, feedback_countdown=0
D0327 00:27:12.102 astrohaven.py:183    Got target_feedback, feedback_countdown=1
D0327 00:27:12.512 astrohaven.py:183    Got target_feedback, feedback_countdown=0
I0327 00:27:15.413 messaging.py:134     PANCHAT I'm takin' it on home and then parking.
D0327 00:27:22.935 mount.py:356         Slewing to home, sleeping for 5 seconds
D0327 00:27:29.956 mount.py:356         Slewing to home, sleeping for 5 seconds
D0327 00:27:40.510 mount.py:356         Slewing to home, sleeping for 5 seconds
I0327 00:27:42.526 ioptron.py:141       Initializing pocs.mount.ioptron mount
I0327 00:27:43.528 ioptron.py:244       Setting up mount for location
D0327 00:27:46.540 serial.py:88         Setting tracking rate to sidereal +00.0000
D0327 00:27:47.041 serial.py:90         Custom tracking rate set
D0327 00:27:47.542 serial.py:94         Tracking response: 1
D0327 00:27:47.543 serial.py:98         Custom tracking rate sent
D0327 00:27:47.543 ioptron.py:212       Setting manual moving rate to max
D0327 00:27:48.545 ioptron.py:214       Mount guide rate: 5050
D0327 00:27:49.548 ioptron.py:220       Mount guide rate: 0.5 0.5
I0327 00:27:49.548 ioptron.py:167       Mount initialized: True
D0327 00:27:49.548 mount.py:228         Setting park position
D0327 00:27:49.559 mount.py:234         LST: 8.011263590162148 hourangle
D0327 00:27:49.559 mount.py:235         HA: -170.0 deg
D0327 00:27:49.560 mount.py:238         RA: 19.344596923495484 hourangle
D0327 00:27:49.560 mount.py:239         Dec: -10.0 deg
D0327 00:27:49.563 mount.py:243         Park Coordinates RA-Dec: <SkyCoord (ICRS): (ra, dec) in deg
    ( 290.16895385, -10.)>
D0327 00:27:49.563 mount.py:266         Setting target coordinates: <SkyCoord (ICRS): (ra, dec) in deg
    ( 290.16895385, -10.)>
D0327 00:27:49.565 ioptron.py:322       RA (ms): 69640548.92458375 ms
D0327 00:27:49.565 ioptron.py:325       Dec (centiarcsec): -3600000.0 carcsec
D0327 00:27:51.068 ioptron.py:187       Slewing to park
D0327 00:28:11.653 mount.py:460         Mount unparked
D0327 00:28:12.154 mount.py:474         Move command: move_south
D0327 00:28:12.155 mount.py:478         Moving south for 11.0 seconds. 
D0327 00:28:25.672 mount.py:483         13.51504099999481 seconds passed before stop
D0327 00:28:26.175 mount.py:485         14.018590999999248 seconds passed total
D0327 00:28:26.175 mount.py:493         Stopping movement
D0327 00:28:28.690 mount.py:368         Mount parked
I0327 00:28:45.094 messaging.py:134     PANCHAT I'm powering down
I0327 00:28:45.095 core.py:225          Shutting down POCS State Machine: , please be patient and allow for exit.
D0327 00:28:45.095 abstract_serial_dome.py:70 Already connected to dome
D0327 00:28:45.522 astrohaven.py:183    Got target_feedback, feedback_countdown=1
D0327 00:28:46.934 astrohaven.py:183    Got target_feedback, feedback_countdown=0
D0327 00:28:47.842 astrohaven.py:183    Got target_feedback, feedback_countdown=1
D0327 00:28:49.255 astrohaven.py:183    Got target_feedback, feedback_countdown=0
I0327 00:28:52.152 core.py:242          Mount is parked, setting Parked state
D0327 00:28:52.152 machine.py:209       Checking safety for set_park
D0327 00:28:52.152 machine.py:214       Always safe to move to set_park
D0327 00:28:52.153 machine.py:253       Before calling set_park from parking state
I0327 00:28:56.859 messaging.py:134     PANCHAT I'm parked now. Phew.
I0327 00:28:56.860 messaging.py:134     PANCHAT No observations found.
I0327 00:28:56.861 messaging.py:134     PANCHAT Going to stay parked for half an hour then will try again.
```

**Comment by wtgee** [comment]
Tracing this down, it looks like it is giving an error while trying to write to the log file in the `rs232.disconnect()` method. Would the `__del__` be called after the log file is closed? @AnthonyHorton saw something similar with the SBIG cameras and the `__del__` dunder and eventually just removed the logging call.

@jamessynge You said this hung for 30 minutes after typing `exit`?

**Comment by wtgee** [comment]
Closing as stale.
