### ISSUE TITLE
pocs_shell raises exception while loading config

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#657]
#648 appears to have broken pocs_shell loading the config on PAN006.

```
(panoptes-env) panoptes@Panmass:/var/panoptes/POCS (develop)$ bin/pocs_shell
Welcome to POCS Shell! Type ? for help
POCS > setup_pocs
Traceback (most recent call last):
  File "bin/pocs_shell", line 904, in <module>
    PocsShell().cmdloop()
  File "/home/panoptes/anaconda3/envs/panoptes-env/lib/python3.6/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/home/panoptes/anaconda3/envs/panoptes-env/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "bin/pocs_shell", line 157, in do_setup_pocs
    observatory = Observatory(simulator=simulator, cameras=cameras)
  File "/var/panoptes/POCS/pocs/observatory.py", line 64, in __init__
    self._create_scheduler()
  File "/var/panoptes/POCS/pocs/observatory.py", line 698, in _create_scheduler
    self.observer, fields_file=fields_path, constraints=constraints)
  File "/var/panoptes/POCS/pocs/scheduler/dispatch.py", line 14, in __init__
    BaseScheduler.__init__(self, *args, **kwargs)
  File "/var/panoptes/POCS/pocs/scheduler/scheduler.py", line 56, in __init__
    if not self.config['scheduler']['check_file']:
KeyError: 'check_file'
```

**Comment by wtgee** [comment]
I suspect you have a `scheduler` config item in your `pocs_local.yaml` so it's not picking up the change to the `pocs.yaml`. Would be nice if we didn't need the whole top-level items just to have changes (mentioned in #564).

I'll get in a fix for this regardless, thanks.
