### ISSUE TITLE
Hanging camera if autofocus_size is too large

### ISSUE THREAD

**Issue by wtgee** [panoptes/POCS#846]
**Describe the bug**
If you set the `autofocus_size` larger than the image it will hang until you manually kill. Then you see an AssertionError.

**Expected behavior**
Handle the error gracefully.

```
In [4]: cam.autofocus()
Out[4]: <threading.Event at 0x7f30c4366fd0>

In [5]: exit
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/storage/miniconda3/envs/panoptes/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/storage/miniconda3/envs/panoptes/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/storage/panoptes/POCS/pocs/focuser/focuser.py", line 353, in _autofocus
    dark=True)
  File "/storage/panoptes/POCS/pocs/camera/camera.py", line 468, in get_thumbnail
    thumbnail = img_utils.crop_data(image, box_width=thumbnail_size)
  File "/storage/panoptes/POCS/pocs/utils/images/__init__.py", line 57, in crop_data
    box_width, data.shape)
AssertionError: Can't clip data, it's smaller than 5000 ((2532, 3352))
```

**Comment by wtgee** [comment]
@AnthonyHorton do we know if this is still an issue?

**Comment by AnthonyHorton** [comment]
@wtgee It probably is. I don't remember putting a check in to prevent the issue.
