### ISSUE TITLE
pocs_shell doesn't work "as is"

### ISSUE THREAD

**Issue by jamessynge** [panoptes/POCS#88]
```bash
panoptes@Panmass:/var/panoptes/POCS$ bin/pocs_shell 
Traceback (most recent call last):
  File "bin/pocs_shell", line 16, in <module>
    from pocs import POCS
ModuleNotFoundError: No module named 'pocs'
panoptes@Panmass:/var/panoptes/POCS$ python bin/pocs_shell
Traceback (most recent call last):
  File "bin/pocs_shell", line 16, in <module>
    from pocs import POCS
ModuleNotFoundError: No module named 'pocs'
```

**Comment by wtgee** [comment]
Closing generic Issue for stale activity. Feel free to reopen or create new Issue if needed.
